### ISSUE TITLE
Failure to parse body is hard to identify

### ISSUE THREAD

**Issue by shadowhand** [middlewares/payload#5]
When the body cannot be parsed the result is an empty HTTP 400 response, with no body. This makes it extremely hard to track where the source of the error is.

**Comment by oscarotero** [comment]
What do you think about including an option to throw the exception instead returns a 400 response.
It could also allow to customize the Exception class to use, for example [HttpErrorException](https://github.com/middlewares/error-handler/blob/master/src/HttpErrorException.php).

**Comment by shadowhand** [comment]
I think it should just skip the try/catch completely and let the exception handler deal with it. But it should use a specific exception type so that it can be handled cleanly.

**Comment by oscarotero** [comment]
Ok, but that should be optional, to keep backward compatibility.

**Comment by oscarotero** [comment]
Instead creating the very specific PayloadErrorException class for this middleware, I was thinking in moving the HttpErrorException from the ErrorHandler middleware to utils, to be reused by other middlewares like this.
It allows to recover the original exception using `$exception->getPrevious()`, provide some hints of the error type (using `$exception->getCode()`) and, optionally, can save some context data using the method `$exception->getContext()`.

What do you think?

**Comment by shadowhand** [comment]
Using a general purpose exception makes it harder to catch. I'm not sure what value `context` would bring here.

**Comment by shadowhand** [comment]
Also worth noting that there will be [JSON exceptions in PHP 7.3](https://ayesh.me/Upgrade-PHP-7.3#json-exceptions).
