### ISSUE TITLE
Cannot disable associative return in JsonPayload

### ISSUE THREAD

**Issue by shadowhand** [middlewares/payload#8]
The definition `JsonPayload::parse(): array` is incompatible with `associative(false)` flag, which could return any scalar type + array + object.

The return type should be dropped.

**Comment by oscarotero** [comment]
Ok, I commited a patch for this. Can you check it?

**Comment by shadowhand** [comment]
Looks good!

**Comment by oscarotero** [comment]
Great. I'm going to release a new version. Thanks!
